title: "Vote IDD ABDULMAJID Vote change"
description: Your local voice for Kilifi South . Standing for change
url: "https://habiboassan.github.io"
baseurl: "/Mptrial"
# logo_url: "/assets/images/path-to-logo.svg"

twitter_username: "twitter_handle"
facebook_username: "facebook_handle"
instagram_username: "instagram_handle"

copyright_name: Copyright name
copyright_link: "/templates/content-page/"

# site_wide_alert:
#   id: 1
#   title: An example alert
#   message: This is an example of a site wide alert message with a [link](/components/site-wide-alert/).

phase: ALPHA
phase_link: https://github.com/habiboassan/Mptrial/issues/1

livereload: true

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-paginate

postcss:
  cache: false

paginate_path: "/news/page:num/"
paginate: 5

permalink: pretty

exclude:
  - LICENSE.txt
  - package-lock.json
  - package.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
  - s3-cloudfront.yml
